#!/usr/bin/env python3
"""Build the United traveler map from a historical categorized export.

The historical "United Flights" export carries, for each ticket, the columns
your team actually coded: Person, Department, and Account. Department is stable
per traveler, so we learn it with confidence; Account varies by trip purpose, so
we record the traveler's most-common account only as a *hint* for review.

Usage:
    python scripts/build_traveler_map.py <historical_export.csv> [out.yml]

Default output: data/united_travelers.yml  (gitignored — contains employee names)
"""

from __future__ import annotations

import csv
import os
import sys
from collections import Counter, defaultdict


def build(path: str) -> dict:
    with open(path, newline="", encoding="utf-8-sig") as fh:
        rows = list(csv.DictReader(fh))

    agg: dict[str, dict[str, Counter]] = defaultdict(
        lambda: {"person": Counter(), "department": Counter(), "account": Counter()}
    )
    for row in rows:
        name = (row.get("Passenger Name") or "").strip()
        if not name:
            continue
        # Skip ancillary-fee rows ("SMITH /SECOND CHECKED BAG"): they inherit the
        # traveler's coding and would pollute the name key.
        if "/" in name and any(w in name.upper() for w in ("BAG", "ZONE", "SEAT")):
            continue
        a = agg[name]
        if row.get("Person", "").strip():
            a["person"][row["Person"].strip()] += 1
        if row.get("Department", "").strip() not in ("", "#N/A"):
            a["department"][row["Department"].strip()] += 1
        if row.get("Account", "").strip():
            a["account"][row["Account"].strip()] += 1

    out = {}
    for name, a in sorted(agg.items()):
        n = sum(a["department"].values()) or sum(a["account"].values())
        dept = a["department"].most_common(1)
        acct = a["account"].most_common(1)
        person = a["person"].most_common(1)
        out[name] = {
            "person": person[0][0] if person else "",
            "department": dept[0][0] if dept else "",
            "department_confidence": round(dept[0][1] / sum(a["department"].values()), 3) if dept else 0,
            "account_hint": acct[0][0] if acct else "",
            "account_confidence": round(acct[0][1] / sum(a["account"].values()), 3) if acct else 0,
            "n": n,
        }
    return out


def dump_yaml(data: dict) -> str:
    # Minimal, dependency-light YAML writer (values are simple scalars).
    lines = ["# Generated by scripts/build_traveler_map.py — do not edit by hand.",
             "# Contains employee names; gitignored by default.", ""]
    for name, v in data.items():
        lines.append(f'"{name}":')
        lines.append(f'  person: "{v["person"]}"')
        lines.append(f'  department: "{v["department"]}"')
        lines.append(f'  department_confidence: {v["department_confidence"]}')
        lines.append(f'  account_hint: "{v["account_hint"]}"')
        lines.append(f'  account_confidence: {v["account_confidence"]}')
        lines.append(f'  n: {v["n"]}')
    return "\n".join(lines) + "\n"


def main(argv):
    if not argv:
        print(__doc__)
        return 1
    src = argv[0]
    out = argv[1] if len(argv) > 1 else os.path.join("data", "united_travelers.yml")
    data = build(src)
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(dump_yaml(data))
    print(f"Wrote {len(data)} travelers to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
